# Generated by Django 3.0.3 on 2021-11-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideways', '0002_auto_20211126_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideway',
            name='trips_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sideway',
            name='trips_timeout',
            field=models.IntegerField(default=0, help_text='Trips accepted but not action maked.'),
        ),
        migrations.AlterField(
            model_name='sideway',
            name='trips_made',
            field=models.IntegerField(default=0, help_text='Trips completed succesfully.'),
        ),
    ]
