# Generated by Django 3.0.3 on 2021-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideways', '0003_auto_20211126_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sideway',
            old_name='trips_made',
            new_name='trips_completed',
        ),
        migrations.AddField(
            model_name='sideway',
            name='trips_accepted',
            field=models.IntegerField(default=0, help_text='Trips that has been accepted.'),
        ),
    ]
