# Generated by Django 3.0.3 on 2021-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideways', '0005_auto_20211126_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideway',
            name='trips_declined',
            field=models.IntegerField(default=0, help_text='Trips that has been declined by the user.'),
        ),
    ]
